
import { backgroundServicePlugin } from './BackgroundServicePlugin';
import { contextAnalyzer } from './ContextAnalyzer';
import { permissionManager } from './PermissionManager';
import { actionExecutor, onProactiveAction } from './ActionExecutor';
import { ProactiveAction, ProactiveActionType } from '../../types/proactive';
import { ProactiveSettings, DEFAULT_PROACTIVE_SETTINGS, AIMindMeshServerSettings } from '../../types';
import { logger } from '../logger';
import { activityLogger } from './ActivityLogger';
import { proactiveNotificationService } from './ProactiveNotificationService';
import { getEventsPendingBriefing, buildBriefingPrompt, markEventBriefed } from './meetingBriefingService';

class ProactiveService {
    private suggestions: ProactiveAction[] = [];
    private listeners: ((suggestions: ProactiveAction[]) => void)[] = [];
    private isInitialized = false;

    // v4.0.0 — server mode state
    private serverModeActive = false;
    private serverModeListeners: ((active: boolean, message?: string) => void)[] = [];

    /** Subscribe to server-mode banner events */
    onServerModeChange(cb: (active: boolean, message?: string) => void): () => void {
        this.serverModeListeners.push(cb);
        return () => { this.serverModeListeners = this.serverModeListeners.filter(l => l !== cb); };
    }

    private notifyServerModeChange(active: boolean, message?: string) {
        this.serverModeListeners.forEach(cb => cb(active, message));
    }

    async init() {
        if (this.isInitialized) return;
        this.isInitialized = true;

        logger.log('info', '[ProactiveService] Initializing...');

        // Initialize notification service with user settings
        const settings = this.getProactiveSettings();
        await proactiveNotificationService.init(settings);

        // If server mode is active, skip native background checks
        if (!this.serverModeActive) {
            backgroundServicePlugin.addListener(this.handlePeriodicCheck.bind(this));
        }

        // Listener for actions generated by Executor (e.g. from other flows)
        onProactiveAction('suggestion', async (action) => {
            this.addSuggestion(action);
        });

        onProactiveAction('chat', async (_action) => {
            // Handled by UI hook
        });
    }

    /**
     * Called when AIMindMesh Server connection is established.
     * Suspends the local on-device background checks.
     */
    enableServerMode(_serverSettings: AIMindMeshServerSettings): void {
        if (this.serverModeActive) return;
        this.serverModeActive = true;
        logger.log('info', '[ProactiveService] Server mode enabled — local proactive suspended');
        this.notifyServerModeChange(true);
    }

    /**
     * Called when the server goes offline (3 consecutive heartbeat failures).
     * Re-enables local on-device background checks as fallback.
     */
    disableServerMode(): void {
        if (!this.serverModeActive) return;
        this.serverModeActive = false;
        logger.log('info', '[ProactiveService] Server offline — switching to local proactive mode');
        // Re-attach listener if not already attached
        backgroundServicePlugin.addListener(this.handlePeriodicCheck.bind(this));
        this.notifyServerModeChange(false, 'Server offline — local proactive mode active');
    }

    private getProactiveSettings(): ProactiveSettings {
        try {
            const settingsStr = localStorage.getItem('proactive-settings');
            if (settingsStr) {
                return JSON.parse(settingsStr);
            }
        } catch (e) {
            logger.log('error', '[ProactiveService] Failed to load settings', e);
        }
        return DEFAULT_PROACTIVE_SETTINGS;
    }

    private async handlePeriodicCheck(timestamp: number) {
        logger.log('info', `[ProactiveService] Handling check at ${timestamp}`);

        const settings = this.getProactiveSettings();
        if (!settings.enabled) return;

        try {
            const context = await contextAnalyzer.analyze();
            logger.log('debug', '[ProactiveService] Context evaluated', context);

            // --- MVP Heuristics ---
            // 1. Low Battery Warning
            if (context.device.batteryLevel < 0.2 && !context.device.isCharging && settings.contextAwareness.respectBatteryLevel) {
                const action: ProactiveAction = {
                    id: `batt-${Date.now()}`,
                    type: ProactiveActionType.SUGGEST_OPTIMIZATION,
                    category: 'suggestive',
                    priority: 8,
                    triggeredAt: Date.now(),
                    triggeredBy: 'system_battery_monitor',
                    expiresAt: Date.now() + 1000 * 60 * 30, // 30m
                    status: 'pending',
                    requiresConfirmation: true,
                    dismissible: true,
                    logLevel: 'info',
                    data: {
                        title: 'Low Battery',
                        message: 'Battery is below 20%. I suggest enabling power saver mode.',
                        action: 'enable_power_saver'
                    }
                };
                await this.processAction(action, context);
            }

            // 2. Overdue Tasks
            if (context.data.overdueTasks.length > 0) {
                const count = context.data.overdueTasks.length;
                const action: ProactiveAction = {
                    id: `overdue-${Date.now()}`,
                    type: ProactiveActionType.SUGGEST_TASK_REVIEW,
                    category: 'suggestive',
                    priority: 5,
                    triggeredAt: Date.now(),
                    triggeredBy: 'system_task_monitor',
                    expiresAt: Date.now() + 1000 * 60 * 60 * 4, // 4h
                    status: 'pending',
                    requiresConfirmation: true,
                    dismissible: true,
                    logLevel: 'info',
                    data: {
                        title: 'Overdue Tasks',
                        message: `You have ${count} overdue tasks. Would you like to review them?`,
                        action: 'review_tasks'
                    }
                };
                // Check if we already have a similar suggestion
                const exists = this.suggestions.some(s => s.type === ProactiveActionType.SUGGEST_TASK_REVIEW);
                if (!exists) {
                    await this.processAction(action, context);
                }
            }

            // 3. Meeting Briefing (5 min before upcoming events)
            if (context.data.upcomingEvents && context.data.upcomingEvents.length > 0) {
                const pendingBriefings = getEventsPendingBriefing(
                    context.data.upcomingEvents,
                    settings.contextAwareness.meetingBriefingLeadTimeMinutes
                );
                for (const event of pendingBriefings) {
                    const action: ProactiveAction = {
                        id: `briefing-${event.id}-${Date.now()}`,
                        type: ProactiveActionType.CHAT_MEETING_BRIEFING,
                        category: 'interactive',
                        priority: 7,
                        triggeredAt: Date.now(),
                        triggeredBy: 'system_calendar_monitor',
                        expiresAt: event.start, // Expires when meeting starts
                        status: 'pending',
                        requiresConfirmation: false,
                        dismissible: true,
                        logLevel: 'info',
                        data: {
                            title: `📋 Meeting Briefing: ${event.title}`,
                            message: buildBriefingPrompt(event),
                            eventId: event.id,
                            eventTitle: event.title,
                            action: 'meeting_briefing'
                        }
                    };
                    markEventBriefed(event.id);
                    await this.processAction(action, context);
                }
            }

            // 4. Memory Maintenance (ONLY when idle or charging, ensuring we don't block user)
            if (context.data.memoryCount > 50 &&
                (context.user.activity === 'idle' || context.device.isCharging) &&
                context.user.activity !== 'active' &&
                settings.permissions.autonomous) {
                const action: ProactiveAction = {
                    id: `mem-maint-${Date.now()}`,
                    type: ProactiveActionType.PERFORM_MEMORY_MAINTENANCE,
                    category: 'autonomous',
                    priority: 3,
                    triggeredAt: Date.now(),
                    triggeredBy: 'system_memory_monitor',
                    expiresAt: undefined,
                    status: 'pending',
                    requiresConfirmation: false,
                    dismissible: false,
                    logLevel: 'info',
                    data: {
                        memoryCount: context.data.memoryCount,
                        action: 'optimize_memory'
                    }
                };
                // Check if we already performed maintenance recently (within last 24h)
                const lastMaintenance = await activityLogger.getLastActionTime(ProactiveActionType.PERFORM_MEMORY_MAINTENANCE);
                const hoursSinceLast = lastMaintenance ? (Date.now() - lastMaintenance) / (1000 * 60 * 60) : 999;
                if (hoursSinceLast > 24) {
                    await this.processAction(action, context);
                }
            }

            // Future: Call LLM to generate actions based on context

            // 4. Context Summarization (when context reaches threshold)
            if (context.chat.contextUsage >= settings.contextAwareness.summarizationThreshold &&
                settings.contextAwareness.enableAutoSummarization &&
                context.chat.messageCount > 10) {
                const action: ProactiveAction = {
                    id: `ctx-sum-${Date.now()}`,
                    type: ProactiveActionType.SUMMARIZE_CONTEXT,
                    category: 'autonomous',
                    priority: 4,
                    triggeredAt: Date.now(),
                    triggeredBy: 'system_context_monitor',
                    expiresAt: undefined,
                    status: 'pending',
                    requiresConfirmation: false,
                    dismissible: false,
                    logLevel: 'info',
                    data: {
                        currentUsage: context.chat.contextUsage,
                        messageCount: context.chat.messageCount,
                        threshold: settings.contextAwareness.summarizationThreshold
                    }
                };
                await this.processAction(action, context);
            }

        } catch (e) {
            logger.log('error', '[ProactiveService] Error in periodic check', e);
        }
    }

    private async processAction(action: ProactiveAction, context: any) {
        const permission = await permissionManager.checkPermission(action.type, context, action.priority);

        if (permission.allowed) {
            if (action.category === 'suggestive') {
                this.addSuggestion(action);
            } else {
                await actionExecutor.execute(action);
            }
        } else {
            logger.log('info', `[ProactiveService] Action blocked: ${permission.reason}`);
            action.status = 'ignored';
            await activityLogger.log(action);
        }
    }

    // --- State Management ---

    getSuggestions() {
        return this.suggestions;
    }

    addSuggestion(action: ProactiveAction) {
        // Deduplicate
        if (this.suggestions.some(s => s.id === action.id)) return;

        this.suggestions = [action, ...this.suggestions];
        this.notifyListeners();

        // Log visibility
        activityLogger.log({ ...action, status: 'pending' });
    }

    dismissSuggestion(id: string) {
        this.suggestions = this.suggestions.filter(s => s.id !== id);
        this.notifyListeners();
        activityLogger.logInteraction(id, 'dismissed');
    }

    async acceptSuggestion(action: ProactiveAction) {
        this.dismissSuggestion(action.id);
        activityLogger.logInteraction(action.id, 'clicked');

        // Execute associated logic
        action.status = 'executing';
        await actionExecutor.execute(action);
    }

    subscribe(callback: (suggestions: ProactiveAction[]) => void) {
        this.listeners.push(callback);
        callback(this.suggestions);
        return () => {
            this.listeners = this.listeners.filter(cb => cb !== callback);
        };
    }

    private notifyListeners() {
        this.listeners.forEach(cb => cb(this.suggestions));
    }
}

export const proactiveService = new ProactiveService();
